export const mockExpectedDataList = [
	{
		name: "vite-reactts-electron-starter",
		version: "0.5.0",
		license: "MIT",
		main: "main/index.js",
		author: {
			name: "Maximilian Stümpfl",
		},
		description:
			"Starter using Vite 2+ React +Typescript + Electron for fast prototyping.",
		keywords: ["vite", "react", "electron", "typescript"],
		repository: {
			url: "https://github.com/lTimeless/vite-reactts-electron-starter",
		},
		productName: "vite-reactts-electron-starter",
		scripts: {
			dev: 'concurrently "yarn dev:vite" " yarn dev:electron"',
			"dev:vite": "vite",
			"dev:electron": "npm run build:electron && electron .",
			build: "npm run build:vite && npm run build:electron",
			"build:vite": "vite build",
			"build:electron": "tsc -p electron",
			dist: "npm run build && electron-builder",
			pack: "npm run build && electron-builder --dir",
			clean: "rimraf dist main src/out",
			"type-check": "tsc",
			lint: "eslint . --ext js,jsx,ts,tsx",
			"lint:fix": "eslint . --ext js,jsx,ts,tsx --fix",
		},
		dependencies: {
			"@emotion/react": "^11.11.1",
			"@mantine/core": "^6.0.20",
			"@mantine/hooks": "^6.0.20",
			"@vitejs/plugin-react": "^1.2.0",
			"electron-is-dev": "^2.0.0",
			react: "^17.0.2",
			"react-dom": "^17.0.2",
			"react-json-view-compare": "^2.0.2",
			vite: "^2.8.6",
		},
		devDependencies: {
			"@types/node": "^17.0.22",
			"@types/react": "^17.0.41",
			"@types/react-dom": "^17.0.14",
			"@typescript-eslint/eslint-plugin": "5.16.0",
			"@typescript-eslint/parser": "5.16.0",
			autoprefixer: "^10.4.4",
			concurrently: "^7.0.0",
			electron: "^17.1.2",
			"electron-builder": "^22.14.13",
			eslint: "8.11.0",
			"eslint-config-airbnb": "19.0.4",
			"eslint-config-prettier": "8.5.0",
			"eslint-plugin-import": "^2.25.4",
			"eslint-plugin-jsx-a11y": "^6.5.1",
			"eslint-plugin-prettier": "4.0.0",
			"eslint-plugin-react": "^7.29.4",
			postcss: "^8.4.12",
			prettier: "2.6.0",
			tailwindcss: "^3.0.23",
			typescript: "^4.6.2",
		},
		build: {
			asar: true,
			files: ["main", "src/out"],
			directories: {
				buildResources: "resources",
			},
		},
	},
	{
		name: "super-2",
		age: 18,
		task: [
			{ name: "eat", time: "09:00" },
			{ name: "work", time: "10:00" },
			{ name: "sleep", time: "22:00" },
		],
	},
	{
		name: "super-3",
		age: 18,
		task: [
			{ name: "eat", time: "09:00" },
			{ name: "work", time: "10:00" },
			{ name: "sleep", time: "22:00" },
		],
	},
	{
		name: "super-4",
		age: 18,
		task: [
			{ name: "eat", time: "09:00" },
			{ name: "work", time: "10:00" },
			{ name: "sleep", time: "22:00" },
		],
	},
	{
		name: "super-5",
		age: 18,
		task: [
			{ name: "eat", time: "09:00" },
			{ name: "work", time: "10:00" },
			{ name: "sleep", time: "22:00" },
		],
	},
];
export const mockActualDataList = [
	{
		name: "chrome-extension-boilerplate-react-vite",
		version: "0.0.1",
		description: "[CMD/CTRL] + SHIFT + S to open",
		license: "MIT",
		repository: {
			type: "git",
			url: "https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite.git",
		},
		scripts: {
			build: "tsc --noEmit && vite build",
			"build:watch": "cross-env __DEV__=true vite build -w",
			"build:hmr":
				"rollup --config utils/reload/rollup.config.ts",
			wss: "node utils/reload/initReloadServer.js",
			dev: "npm run build:hmr && (run-p wss build:watch)",
			test: "jest",
		},
		type: "module",
		dependencies: {
			"@radix-ui/react-checkbox": "^1.0.4",
			"@radix-ui/react-dialog": "^1.0.4",
			"@radix-ui/react-dropdown-menu": "^2.0.5",
			"@radix-ui/react-icons": "^1.3.0",
			"@radix-ui/react-popover": "^1.0.6",
			"@radix-ui/react-slot": "^1.0.2",
			"@reduxjs/toolkit": "^1.9.5",
			"@tanstack/react-table": "^8.9.3",
			"class-variance-authority": "^0.7.0",
			clsx: "^2.0.0",
			cmdk: "^0.2.0",
			"construct-style-sheets-polyfill": "^3.1.0",
			"lucide-react": "^0.268.0",
			react: "18.2.0",
			"react-dom": "18.2.0",
			"react-redux": "^8.1.2",
			"react-tooltip": "^5.21.1",
			"tailwind-merge": "^1.14.0",
			"tailwindcss-animate": "^1.0.6",
		},
		devDependencies: {
			"@rollup/plugin-typescript": "^8.5.0",
			"@testing-library/react": "13.4.0",
			"@twind/core": "^1.1.3",
			"@twind/preset-autoprefix": "^1.0.7",
			"@twind/preset-tailwind": "^1.1.4",
			"@types/chrome": "0.0.224",
			"@types/jest": "29.0.3",
			"@types/node": "^20.5.1",
			"@types/react": "18.0.21",
			"@types/react-dom": "18.2.4",
			"@types/ws": "^8.5.4",
			"@typescript-eslint/eslint-plugin": "5.56.0",
			"@typescript-eslint/parser": "5.38.1",
			"@vitejs/plugin-react": "2.2.0",
			autoprefixer: "^10.4.15",
			chokidar: "^3.5.3",
			"cross-env": "^7.0.3",
			eslint: "8.36.0",
			"eslint-config-prettier": "^8.5.0",
			"eslint-plugin-prettier": "4.2.1",
			"eslint-plugin-react": "7.32.2",
			"fs-extra": "11.1.0",
			jest: "29.0.3",
			"jest-environment-jsdom": "29.5.0",
			"npm-run-all": "^4.1.5",
			postcss: "^8.4.28",
			prettier: "2.8.8",
			rollup: "2.79.1",
			sass: "1.62.1",
			tailwindcss: "^3.3.3",
			"ts-jest": "29.0.2",
			"ts-loader": "9.4.2",
			typescript: "4.8.3",
			vite: "3.1.3",
			ws: "8.13.0",
		},
	},
	{
		name: "coolapt-2",
		age: 20,
		task: [
			{ name: "eat", time: "09:00" },
			{ name: "work", time: "10:00" },
			{ name: "sleep", time: "23:00" },
			{ name: "running", time: "08:00" },
		],
	},
	{
		name: "coolapt-3",
		age: 20,
		task: [
			{ name: "eat", time: "09:00" },
			{ name: "work", time: "10:00" },
			{ name: "sleep", time: "23:00" },
			{ name: "running", time: "08:00" },
		],
	},
	{
		name: "coolapt-4",
		age: 20,
		task: [
			{ name: "eat", time: "09:00" },
			{ name: "work", time: "10:00" },
			{ name: "sleep", time: "23:00" },
			{ name: "running", time: "08:00" },
		],
	},
	{
		name: "coolapt-5",
		age: 20,
		task: [
			{ name: "eat", time: "09:00" },
			{ name: "work", time: "10:00" },
			{ name: "sleep", time: "23:00" },
			{ name: "running", time: "08:00" },
		],
	},
];
